name: Build and test
on:
  push:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'README.md'
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: unit tests for xUnit Helpers
      uses: zyborg/dotnet-tests-report@v1
      with:
        report_name: xunit-helper-tests
        report_title: xUnit Helpers Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gist_name: xunit-helper-tests.md
        gist_badge_label: 'xUnit Helpers: %Counters_passed%/%Counters_total%'
        gist_token: ${{ secrets.GIST_TOKEN }}
        set_check_status_from_test_outcome: true
